# Generated by Django 3.0.7 on 2020-06-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('emp_code', models.IntegerField(max_length=50)),
                ('mobile', models.IntegerField(max_length=10)),
                ('Position', models.CharField(max_length=50)),
            ],
        ),
    ]
