# Generated by Django 3.0.7 on 2020-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='action',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
